version: "3.2"
services:

  parse-server:
    image: innocells/parse-server
    volumes:
      - ./server/:/parse-server/server/
    links:
      - mongo
    ports:
      - "80:8080"
    environment:
      - PARSE_SERVER_APP_ID
      - PARSE_SERVER_APP_NAME
      - PARSE_SERVER_MASTER_KEY
      - PARSE_SERVER_URL
      - PARSE_SERVER_DASHBOARD_USER
      - PARSE_SERVER_DASHBOARD_PASSWORD

  mongo:
    image: mongo
    ports:
      - "27017:27017"