parse-server:
  image: innocells/parse-server
  links:
    - mongo
  ports:
    - "1337:1337"
  environment:
    PORT: 1337
    PARSE_SERVER_APPLICATION_ID:
    PARSE_SERVER_MASTER_KEY:
    PARSE_SERVER_HOST:
    PARSE_SERVER_DATABASE_URI: 'mongodb://mongo/parse-server'
    PARSE_SERVER_DATABASE_OPTIONS:
    PARSE_SERVER_COLLECTION_PREFIX:
    PARSE_SERVER_URL:
    PARSE_PUBLIC_SERVER_URL:
    PARSE_SERVER_CLIENT_KEY:
    PARSE_SERVER_JAVASCRIPT_KEY:
    PARSE_SERVER_REST_API_KEY:
    PARSE_SERVER_DOT_NET_KEY:
    PARSE_SERVER_WEBHOOK_KEY:
    PARSE_SERVER_CLOUD_CODE_MAIN:
    PARSE_SERVER_PUSH:
    PARSE_SERVER_SCHEDULED_PUSH:
    PARSE_SERVER_OAUTH_PROVIDERS:
    PARSE_SERVER_AUTH_PROVIDERS:
    PARSE_SERVER_FILE_KEY:
    PARSE_SERVER_FACEBOOK_APP_IDS:
    PARSE_SERVER_ENABLE_ANON_USERS:
    PARSE_SERVER_ALLOW_CLIENT_CLASS_CREATION:
    PARSE_SERVER_MOUNT_PATH:
    PARSE_SERVER_FILES_ADAPTER:
    PARSE_SERVER_EMAIL_ADAPTER:
    PARSE_SERVER_VERIFY_USER_EMAILS:
    PARSE_SERVER_PREVENT_LOGIN_WITH_UNVERIFIED_EMAIL:
    PARSE_SERVER_EMAIL_VERIFY_TOKEN_VALIDITY_DURATION:
    PARSE_SERVER_ACCOUNT_LOCKOUT:
    PARSE_SERVER_PASSWORD_POLICY:
    PARSE_SERVER_APP_NAME:
    PARSE_SERVER_LOGGER_ADAPTER:
    PARSE_SERVER_CUSTOM_PAGES:
    PARSE_SERVER_MAX_UPLOAD_SIZE:
    PARSE_SERVER_SESSION_LENGTH:
    VERBOSE:
    JSON_LOGS:
    PARSE_SERVER_LOG_LEVEL:
    PARSE_SERVER_LOGS_FOLDER:
    PARSE_SERVER_REVOKE_SESSION_ON_PASSWORD_RESET:
    PARSE_SERVER_SCHEMA_CACHE_TTL:
    PARSE_SERVER_ENABLE_SINGLE_SCHEMA_CACHE:
    PARSE_SERVER_CLUSTER:
    PARSE_SERVER_LIVE_QUERY_OPTIONS:

mongo:
  image: mongo
  ports:
    - "27017:27017"

parse-dashboard:
  image: innocells/parse-dashboard
  links:
    - parse-server
  ports:
    - "4040:4040"
  environment:
    PARSE_DASHBOARD_SERVER_URL: 'http://localhost:1337/parse'
    PARSE_DASHBOARD_MASTER_KEY: $PARSE_SERVER_MASTER_KEY
    PARSE_DASHBOARD_APP_ID: $PARSE_SERVER_APPLICATION_ID
    PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: 1
    PARSE_DASHBOARD_USER_ID: $PARSE_SERVER_APPLICATION_ID
    PARSE_DASHBOARD_USER_PASSWORD: $PARSE_SERVER_MASTER_KEY