version: "3.2"
services:

  parse-server:
    image: innocells/parse-server
    volumes:
      - ./server/:/parse-server/server/
    links:
      - mongo
    ports:
      - "80:8080"

  mongo:
    image: mongo
    ports:
      - "27017:27017"